window.setDT = function(t){ S.detalleTab=t; init_detalle_causa(); };

window.init_detalle_causa = function() {
  const o=S.solicitudes.find(x=>x.id===S.detailId);
  const container = document.getElementById('detalle-container');
  if(!o){ container.innerHTML = '<div class="alert alert-warning">'+ic('alertC',16)+' Solicitud no encontrada.</div>'; return;}
  if(S.user?.role === 'perito' && !o.peritos.includes(S.user.name)) {
      container.innerHTML = '<div class="alert alert-warning" style="margin-top: 1rem;">'+ic('lock',16)+' <strong>Acceso denegado:</strong> Esta solicitud pertenece a otro perito y usted no tiene permisos para verla.</div>'; return;
  }
  const notas=S.notas[S.detailId]||[];
  const tabs={info:renderDetalleInfo(o,notas), historial:renderDetalleHist(o), archivos:renderDetalleArchivos(o)};
  container.innerHTML = '<div style="display:flex;align-items:center;gap:6px;font-size:13px;color:var(--muted-fg);margin-bottom:16px;"><button class="btn-icon" onclick="nav(\'causas\')">'+ic('arrowL',15)+'</button><span style="cursor:pointer;" onclick="nav(\'causas\')">Consulta de Solicitudes</span><span style="display:flex;">'+ic('chevR',13)+'</span><span class="mono" style="color:var(--fg);font-weight:500;font-size:12px;">'+esc(o.id)+'</span></div><div class="detalle-hero"><div class="dhm"><span style="background:rgba(255,255,255,.15);color:white;padding:3px 12px;border-radius:999px;font-size:12px;font-weight:700;font-family:monospace;">'+esc(o.id)+'</span>'+bdg(o.estado)+ubdg(o.urgencia)+'</div><h2 style="font-size:18px;font-weight:700;color:white;margin-bottom:4px;">'+esc(o.imputado)+' s/ '+esc(o.delito)+'</h2><p style="font-size:14px;color:rgba(255,255,255,.65);">'+esc(o.fiscal)+' — '+esc(o.jur)+'</p></div>'+(o.peritos.length===0?'<div class="alert alert-warning">'+ic('alertC',16,'#A16207')+' <span><strong>Sin perito asignado.</strong> Esta solicitud requiere asignaci\u00f3n.</span></div>':'<div class="alert alert-info">'+ic('user',16,'#1D4ED8')+' <span><strong>Perito/s:</strong> '+esc(o.peritos.join(', '))+' — Pericia en curso</span></div>')+'<div class="tabs"><button class="tab-btn'+(S.detalleTab==='info'?' active':'')+'" onclick="setDT(\'info\')">Informaci\u00f3n</button><button class="tab-btn'+(S.detalleTab==='historial'?' active':'')+'" onclick="setDT(\'historial\')">Historial ('+o.hist.length+')</button><button class="tab-btn'+(S.detalleTab==='archivos'?' active':'')+'" onclick="setDT(\'archivos\')">Archivos</button></div>'+(tabs[S.detalleTab]||'');
};

function renderDetalleInfo(o,notas){ return '<div class="detail-grid"><div><div class="card"><div class="card-head"><div class="card-title">Datos de la solicitud</div></div>'+[{ic:'hash',l:'N\u00b0 Solicitud',v:o.id},{ic:'file',l:'N\u00b0 Expediente',v:o.exp},{ic:'pin',l:'Jurisdicci\u00f3n',v:o.jur},{ic:'cal',l:'Fecha ingreso',v:o.ingreso},{ic:'clock',l:'Vencimiento',v:o.venc},{ic:'tag',l:'Urgencia',v:o.urgencia.charAt(0).toUpperCase()+o.urgencia.slice(1)}].map(r=>'<div class="detail-row"><div>'+ic(r.ic,14,'var(--muted-fg)')+'</div><div><div class="detail-lbl">'+r.l+'</div><div class="detail-val">'+esc(r.v)+'</div></div></div>').join('')+'</div><div class="card mt-4"><div class="card-head"><div class="card-title">Partes procesales</div></div>'+[{l:'Imputado/a',v:o.imputado},{l:'V\u00edctima',v:o.victima},{l:'Delito investigado',v:o.delito},{l:'Fiscal requirente',v:o.fiscal}].map(r=>'<div class="detail-row"><div><div class="detail-lbl">'+r.l+'</div><div class="detail-val">'+esc(r.v)+'</div></div></div>').join('')+'</div></div><div><div class="card"><div class="card-head"><div class="card-title">Asignaci\u00f3n pericial</div>'+(S.user?.role==='mesa'?'<button class="btn btn-primary btn-sm" onclick="openAM(\''+o.id+'\')">'+ic('edit',13,'white')+' '+(o.peritos.length>0?'Editar':'Asignar')+'</button>':'')+'</div>'+[{l:'Peritos responsables',v:o.peritos.length>0?o.peritos.join(', '):'Sin asignar'},{l:'Fecha/hora apertura de informe',v:o.fhi?fmtDT(o.fhi):'No programada'},{l:'N\u00b0 Interno',v:o.id}].map(r=>'<div class="detail-row"><div><div class="detail-lbl">'+r.l+'</div><div class="detail-val" style="color:'+(r.v.includes('Sin')||r.v.includes('No')?'var(--muted-fg)':'var(--fg)')+';">'+esc(r.v)+'</div></div></div>').join('')+'</div><div class="card mt-4"><div class="card-head"><div class="card-title">Secuestros recibidos</div></div><div class="card-body"><p style="font-size:13px;line-height:1.7;">'+esc(o.secuestros)+'</p></div></div><div class="card mt-4"><div class="card-head"><div class="card-title">Tareas solicitadas</div></div><div class="card-body"><p style="font-size:13px;line-height:1.7;">'+esc(o.tareas)+'</p></div></div>'+'</div></div>'; }

function renderDetalleHist(o){ return '<div class="card"><div class="card-head"><div class="card-title">Historial de movimientos</div></div><div class="card-body">'+(o.hist.length===0?'<p style="color:var(--muted-fg);">Sin historial.</p>':'<div class="timeline">'+o.hist.map(h=>'<div class="t-item"><div class="t-dot" style="background:'+h.c+';box-shadow:0 0 0 2px '+h.c+'30;"></div><div class="t-event">'+esc(h.e)+'</div><div class="t-meta">'+ic('cal',10)+' '+esc(h.f)+'&nbsp;·&nbsp;'+ic('user',10)+' '+esc(h.u)+'</div></div>').join('')+'</div>')+'</div></div>'; }

function renderDetalleArchivos(o){ const files=[{n:'Solicitud_'+o.id+'.pdf',t:'PDF',f:o.ingreso,s:'2.4 MB'},{n:'Acta_secuestro_'+o.exp+'.pdf',t:'PDF',f:o.ingreso,s:'1.1 MB'}]; return '<div class="card"><div class="card-head"><div class="card-title">Archivos adjuntos</div>'+(S.user?.role!=='coordinador'?'<button class="btn btn-ghost btn-sm">'+ic('clip',13)+' Adjuntar</button>':'')+'</div><div class="card-body">'+files.map(a=>'<div style="display:flex;align-items:center;gap:14px;padding:12px 0;border-bottom:1px solid var(--border);"><div style="width:36px;height:36px;background:#FEF2F2;border-radius:var(--radius);display:flex;align-items:center;justify-content:center;flex-shrink:0;">'+ic('file',16,'#DC2626')+'</div><div style="flex:1;"><div style="font-size:13px;font-weight:500;">'+esc(a.n)+'</div><div style="font-size:11px;color:var(--muted-fg);">'+a.t+' · '+a.s+' · '+a.f+'</div></div><button class="btn-icon">'+ic('dl',15)+'</button></div>').join('')+'</div></div>'; }